language: python
python:
- 2.7
- 3.5
- 3.6
- 3.7
install:
- pip install -U setuptools
- pip install -r requirements-dev.txt #fix versions
- python setup.py develop
script:
- py.test --cov skosprovider_atramhasis --cov-report term-missing tests
after_success:
- coveralls
